// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MiniSiniestros.Data;

#nullable disable

namespace MiniSiniestros.Data.Migrations.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260718232705_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MiniSiniestros.Entities.Empleador", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Cuit")
                        .IsRequired()
                        .HasMaxLength(11)
                        .HasColumnType("nvarchar(11)");

                    b.Property<string>("RazonSocial")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.HasKey("Id");

                    b.ToTable("Empleadores");
                });

            modelBuilder.Entity("MiniSiniestros.Entities.HistorialEstadoSiniestro", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("EstadoAnterior")
                        .HasColumnType("int");

                    b.Property<int>("EstadoNuevo")
                        .HasColumnType("int");

                    b.Property<DateTime>("FechaCambio")
                        .HasColumnType("datetime2");

                    b.Property<int>("SiniestroId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("SiniestroId");

                    b.ToTable("HistorialEstadosSiniestros");
                });

            modelBuilder.Entity("MiniSiniestros.Entities.NotificacionSrt", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Exitosa")
                        .HasColumnType("bit");

                    b.Property<DateTime>("FechaEnvio")
                        .HasColumnType("datetime2");

                    b.Property<string>("MensajeError")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("SiniestroId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("SiniestroId");

                    b.ToTable("NotificacionesSrt");
                });

            modelBuilder.Entity("MiniSiniestros.Entities.PrestadorMedico", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.HasKey("Id");

                    b.ToTable("PrestadoresMedicos");
                });

            modelBuilder.Entity("MiniSiniestros.Entities.Siniestro", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("EmpleadorId")
                        .HasColumnType("int");

                    b.Property<int>("Estado")
                        .HasColumnType("int");

                    b.Property<DateTime>("FechaAlta")
                        .HasColumnType("datetime2");

                    b.Property<string>("NumeroSiniestro")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("TrabajadorId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("EmpleadorId");

                    b.HasIndex("TrabajadorId");

                    b.ToTable("Siniestros");
                });

            modelBuilder.Entity("MiniSiniestros.Entities.SiniestroPrestador", b =>
                {
                    b.Property<int>("SiniestroId")
                        .HasColumnType("int");

                    b.Property<int>("PrestadorMedicoId")
                        .HasColumnType("int");

                    b.Property<DateTime>("FechaAsignacion")
                        .HasColumnType("datetime2");

                    b.HasKey("SiniestroId", "PrestadorMedicoId");

                    b.HasIndex("PrestadorMedicoId");

                    b.ToTable("SiniestrosPrestadores");
                });

            modelBuilder.Entity("MiniSiniestros.Entities.Trabajador", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Apellido")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Cuil")
                        .IsRequired()
                        .HasMaxLength(11)
                        .HasColumnType("nvarchar(11)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Trabajadores");
                });

            modelBuilder.Entity("MiniSiniestros.Entities.HistorialEstadoSiniestro", b =>
                {
                    b.HasOne("MiniSiniestros.Entities.Siniestro", "Siniestro")
                        .WithMany("HistorialEstados")
                        .HasForeignKey("SiniestroId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Siniestro");
                });

            modelBuilder.Entity("MiniSiniestros.Entities.NotificacionSrt", b =>
                {
                    b.HasOne("MiniSiniestros.Entities.Siniestro", "Siniestro")
                        .WithMany("NotificacionesSrt")
                        .HasForeignKey("SiniestroId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Siniestro");
                });

            modelBuilder.Entity("MiniSiniestros.Entities.Siniestro", b =>
                {
                    b.HasOne("MiniSiniestros.Entities.Empleador", "Empleador")
                        .WithMany("Siniestros")
                        .HasForeignKey("EmpleadorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MiniSiniestros.Entities.Trabajador", "Trabajador")
                        .WithMany("Siniestros")
                        .HasForeignKey("TrabajadorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Empleador");

                    b.Navigation("Trabajador");
                });

            modelBuilder.Entity("MiniSiniestros.Entities.SiniestroPrestador", b =>
                {
                    b.HasOne("MiniSiniestros.Entities.PrestadorMedico", "PrestadorMedico")
                        .WithMany("Siniestros")
                        .HasForeignKey("PrestadorMedicoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MiniSiniestros.Entities.Siniestro", "Siniestro")
                        .WithMany("Prestadores")
                        .HasForeignKey("SiniestroId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PrestadorMedico");

                    b.Navigation("Siniestro");
                });

            modelBuilder.Entity("MiniSiniestros.Entities.Empleador", b =>
                {
                    b.Navigation("Siniestros");
                });

            modelBuilder.Entity("MiniSiniestros.Entities.PrestadorMedico", b =>
                {
                    b.Navigation("Siniestros");
                });

            modelBuilder.Entity("MiniSiniestros.Entities.Siniestro", b =>
                {
                    b.Navigation("HistorialEstados");

                    b.Navigation("NotificacionesSrt");

                    b.Navigation("Prestadores");
                });

            modelBuilder.Entity("MiniSiniestros.Entities.Trabajador", b =>
                {
                    b.Navigation("Siniestros");
                });
#pragma warning restore 612, 618
        }
    }
}
